FROM ubuntu:22.04

RUN apt update 


RUN apt install -y dotnet-sdk-8.0

RUN apt install dotnet-runtime-8.0

RUN echo Y|apt install git


RUN git clone  https://github.com/Pica4uca/Repos.git

RUN dotnet dev-certs https --trust

WORKDIR /Repos/ValidNumb/ValidNumb

ENTRYPOINT [ "dotnet","test" ]
